development:
  admin_email: admin@boltmade.com
  admin_password: changeme
  secret_key_base: Settings.secret_key_base

test:
  secret_key_base: Settings.secret_key_base

production:
  admin_email: Settings.admin_email
  admin_password: Settings.password
  secret_key_base: Settings.secret_key_base
